export const metadata = {
  title: "Account",
  description: "Generated by Next.js",
};

export default function Page() {
  return <h2 className="font-semibold text-2xl text-colors-accent-400 mb-7">
    Welcome, Priyanshu
  </h2>
}
